export const JWT_ACCESS_TOKEN_EXPIRE_SECONDS = 2592000; // 1800
export const JWT_REFRESH_TOKEN_EXPIRE_SECONDS = 2592000;

export const ADMIN_ROLE = 'ADMIN';
export const CUSTOMER_ROLE = 'CUSTOMER';

export const PAGE_DEFAULT = 1;
export const PAGE_SIZE_DEFAULT = 10;
