POST http://localhost:8000/v1/auth/register/
Content-Type: application/json

{
    "email": "khuy220@gmail.com",
    "password": "123"
}

### Login
POST  http://localhost:8000/v1/auth/login/
Content-Type: application/json

{
    "email": "khuy220@gmail.com",
    "password": "123"
}

### Refresh token
POST  http://localhost:8000/v1/auth/refresh-token/
Content-Type: application/json
 

### Logout
DELETE   http://localhost:8000/v1/auth/logout/


### Add user
POST   http://localhost:8000/v1/users/
Content-Type: application/json

{
    "email": "email5@gmail.com",
    "firstName": "Hai",
    "lastName": "Bui Khanh",
    "roleName": "ADMIN",
    "professionId": 2
}

### Get user
GET http://localhost:8000/v1/users/
 